version: "3"

services:
  server:
    build: .
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    volumes:
      - /opt/redis_data/password_manager:/data
    command: redis-server --save 60 1 --loglevel warning